### ISSUE TITLE
Could not pass GameInitializationEvent -- Config directory already exists

### ISSUE THREAD

**Issue by AlexandreGerault** [AlexandreGerault/battleroyale#1]
# Expected Behavior

I expect the server to run normally, without throwing an error when the plugin is loaded.

# Current Behavior

When the plugin is loaded, it throws an error saying that it could not pass the GameInitializationEvent.

## Steps to Reproduce

To reproduce this issue, just follow these steps:

1. Remove any brp folder in the config directory
2. Start the server (with the plugin in the mods folder)
3. Stop and restart the server

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Sponge Version: Sponge-1.12.2-7.1.7
* Plugin Version: 1.0.0-SNAPSHOT
* SDK version: JAVA_8

## Failure Logs

Please include any relevant log snippets or files here.
```
[22:11:20 ERROR] [Sponge]: Could not pass GameInitializationEvent$Impl to Plugin{id=brp, name=Battle Royale, version=1.0, description=Battle royal plugin, source=mods\brp-1.0.0-SNAPSHOT.jar}
java.lang.RuntimeException: null
        at io.github.alexandregerault.battleroyale.main.BattleRoyale.onInit(BattleRoyale.java:99) ~[BattleRoyale.class:?]
        at org.spongepowered.common.event.listener.GameInitializationEventListener_BattleRoyale_onInit3.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-7.1.7]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:433) ~[SpongeEventManager.class:1.12.2-7.1.7]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:478) ~[SpongeEventManager.class:1.12.2-7.1.7]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:259) ~[SpongeImpl.class:1.12.2-7.1.7]
        at org.spongepowered.common.SpongeImpl.postState(SpongeImpl.java:267) ~[SpongeImpl.class:1.12.2-7.1.7]
        at org.spongepowered.server.SpongeVanilla.initialize(SpongeVanilla.java:157) ~[SpongeVanilla.class:1.12.2-7.1.7]
        at net.minecraft.server.dedicated.DedicatedServer.handler$vanilla$onServerInitialize$zpa000(SourceFile:2248) ~[nz.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(SourceFile:191) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.run(SourceFile:434) ~[MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
```

**Comment by AlexandreGerault** [comment]
This occurs because of these lines in the main plugin class:
```java
if(this.schematicsDir.mkdirs())
	this.state = GameState.LOBBY;
else
	this.logger().info("Config dir already exists");
```

**Comment by AlexandreGerault** [comment]
The issue should be fixed.
